package com.dlabs.acs.entity.assessement.enumeration;

public enum ParticipantStatus {
	REGISTERED,INVITATION_SENT, INVITATION_ACCEPTED, INVITATION_REJECTED, DECLINED_BEFORE_TEST, DECLINE_DURING_TEST, SESSION_I, SESSION_II, PARTICIPANT_FINISH, ASSIGNED_TO_ASSESSOR, PARTIAL_RATING, ASSESSEMENT_COMPLETE;
}
